name: Terraform Azure Pipeline

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: list all files
      run: ls -lha

    - name: Terraform Init
      run: terraform -chdir="./resources/dev" init
    - name: Import module
      run: terraform import module.rg-challenge-dev.azurerm_resource_group.rg /subscriptions/0a023d0f-c65f-475e-8e05-b70b5902ab84/resourceGroups/rg-challenge-dev-kiq

    - name: Terraform Plan
      run: terraform -chdir="./resources/dev" plan

    - name: Terraform Apply
      run: terraform -chdir="./resources/dev" apply -auto-approve
